// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"http-api/app/models/roles"
	"time"
)

//  创建公司参数
type CreateCompanyInput struct {
	//  公司名
	Name string `json:"name"`
	//  公司名称拼写简写
	PinYin string `json:"pinYin"`
	//   宗旨
	Symbol string `json:"symbol"`
	//  logo 文件Id
	LogoFileID int `json:"logoFileId"`
	//  App 背景图片Id
	BackgroundFileID int `json:"backgroundFileId"`
	//  账号状态
	IsAble bool `json:"isAble"`
	//  公司的电话
	Phone string `json:"phone"`
	//  公司的微信
	Wechat string `json:"wechat"`
	//  开始时间
	StartedAt string `json:"startedAt"`
	//  结束时间
	EndedAt string `json:"endedAt"`
	//  管理员名称
	AdminName string `json:"adminName"`
	//  管理员手机
	AdminPhone string `json:"adminPhone"`
	//  管理员密码
	AdminPassword string `json:"adminPassword"`
	//  管理员微信
	AdminWechat string `json:"adminWechat"`
	//  管理员头像Id
	AdminAvatarFileID int `json:"adminAvatarFileId"`
}

type CreateCompanyRes struct {
	ID int `json:"id"`
	//  公司名
	Name string `json:"name"`
	//  用于型钢编码生成
	PinYin string `json:"pinYin"`
	//  APP 企业宗旨
	Symbol string `json:"symbol"`
	//  logo文件
	LogoFile *SingleUploadRes `json:"logoFile"`
	//  app背景文件
	BackgroundFile *SingleUploadRes `json:"backgroundFile"`
	//  账号状态
	IsAble bool `json:"isAble"`
	//  公司的电话
	Phone string `json:"phone"`
	//  公司的微信
	Wechat string `json:"wechat"`
	//  开始时间
	StartedAt time.Time `json:"startedAt"`
	//  结束时间
	EndedAt time.Time `json:"endedAt"`
	//  管理员名称
	AdminName string `json:"adminName"`
	//  创建时间
	CreatedAt time.Time `json:"createdAt"`
}

//  修改公司参数
type EditCompanyInput struct {
	//  公司ID
	ID int `json:"id"`
	//  公司名
	Name string `json:"name"`
	//  公司名称拼写简写
	PinYin string `json:"pinYin"`
	//   宗旨
	Symbol string `json:"symbol"`
	//  logo 文件Id
	LogoFileID int `json:"logoFileId"`
	//  App 背景图片Id
	BackgroundFileID int `json:"backgroundFileId"`
	//  账号状态
	IsAble bool `json:"isAble"`
	//  公司的电话
	Phone string `json:"phone"`
	//  公司的微信
	Wechat string `json:"wechat"`
	//  开始时间
	StartedAt string `json:"startedAt"`
	//  结束时间
	EndedAt string `json:"endedAt"`
	//  管理员名称
	AdminName string `json:"adminName"`
	//  管理员手机
	AdminPhone string `json:"adminPhone"`
	//  管理员密码
	AdminPassword *string `json:"adminPassword"`
	//  管理员微信
	AdminWechat string `json:"adminWechat"`
	//  管理员头像Id
	AdminAvatarFileID int `json:"adminAvatarFileId"`
}

type LoginRes struct {
	//  授权token
	AccessToken string `json:"accessToken"`
	//  过期时间戳(秒 7天)
	Expired int `json:"expired"`
	//  角色标识
	Role roles.GraphqlRole `json:"role"`
	//  角色名
	RoleName string `json:"roleName"`
}

type SingleUploadRes struct {
	//  文件ID
	ID int `json:"id"`
	//  文访问链接
	URL string `json:"url"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
